# Generated by Django 4.1.7 on 2023-04-07 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='basket',
            name='count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
