name: Django CI

on:
  push:
    branches: [ test_pipelines ]
  pull_request:
    branches: [ test_pipelines ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.9 ]

    services:
      db:
        image: postgres:12.0-alpine
        volumes:
          - postgres_data:/app
        env:
          POSTGRES_USER=$POSTGRES_USER
          POSTGRES_PASSWORD=$POSTGRES_PASSWORD
          POSTGRES_DB=$POSTGRES_DATABASE_NAME
        ports: ['5432:5432']
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r shop_project/requirements.txt

    - name: Lint with Prospector
      run: |
        prospector || true

    - name: Set up .env
      run: |
        echo "${{ secrets.ENV_FILE }}" > shop_project/.env

    - name: Run Tests

      run: |
        cd shop_project
        pytest